on:
  workflow_dispatch:
name: money
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: python3-pip install yq
      - run: |
          echo '["Name", "Code", "Num", "Scale"]' | jq -r '. | @csv' > currency_data.new.csv
          curl -sSL https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml | xq '.ISO_4217.CcyTbl.CcyNtry' | jq '(.. | select(has("Ccy")?)) | (if .CcyMnrUnts=="N.A." then .CcyMnrUnts="0" else . end) | (if .CcyNm | type=="object" then .CcyNm |= .["#text"] else .CcyNm |= . end)' | jq -r '[.CcyNm, .Ccy, .CcyNbr, .CcyMnrUnts] | @csv' >> currency_data.new.csv
      - id: changed
        run: echo "CHANGED=$(diff -bw currency_data.new.csv scripts/currency/currency_data.csv && echo true || echo false" >> $GITHUB_OUTPUT
      - name: "Modify csv file if currencies has been changed"
        run: |
          git checkout -b "currency-update-$(date --iso-8601=date)-${{ github.run_number }}-${{ github.run_attempt }}"
          mv currency_data.new.csv scripts/currency/currency_data.csv
          git add -u
          git commit -m "update currencies list"
      - name: "Create PR if currencies has been changed"
        if: ${{ steps.changed.outputs.CHANGED }}
        run: |
          gh pr create -B main -H "currency-update-$(date --iso-8601=date)-${{ github.run_number }}-${{ github.run_attempt }}" --title 'Merge "currency-update-$(date --iso-8601=date)-${{ github.run_number }}-${{ github.run_attempt }}" into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
